/* Generated by AN DISI Unibo */ 
package it.unibo.calibration

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Calibration ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("###CALIBRATION STARTED")
						delay(10000) 
					}
					 transition( edgeName="goto",targetState="forwardCalibration", cond=doswitch() )
				}	 
				state("forwardCalibration") { //this:State
					action { //it:State
						println("###START FORWARD CALIBRATION")
						delay(5000) 
						forward("modelChangeAction", "modelChangeAction(robot,w)" ,"butlerresourcemodel" ) 
						delay(780) 
						forward("modelChangeAction", "modelChangeAction(robot,h)" ,"butlerresourcemodel" ) 
						delay(3000) 
						println("###FORWARD CALIBRATION TERMINATED")
					}
					 transition( edgeName="goto",targetState="leftCalibration", cond=doswitch() )
				}	 
				state("leftCalibration") { //this:State
					action { //it:State
						delay(5000) 
						println("###START LEFT CALIBRATION")
						forward("modelChangeAction", "modelChangeAction(robot,a)" ,"butlerresourcemodel" ) 
						delay(870) 
						forward("modelChangeAction", "modelChangeAction(robot,h)" ,"butlerresourcemodel" ) 
						delay(3000) 
						println("###LEFT CALIBRATION TERMINATED")
					}
					 transition( edgeName="goto",targetState="rightCalibration", cond=doswitch() )
				}	 
				state("rightCalibration") { //this:State
					action { //it:State
						println("###START RIGHT CALIBRATION")
						delay(5000) 
						forward("modelChangeAction", "modelChangeAction(robot,d)" ,"butlerresourcemodel" ) 
						delay(850) 
						forward("modelChangeAction", "modelChangeAction(robot,h)" ,"butlerresourcemodel" ) 
						delay(3000) 
						forward("modelChangeAction", "modelChangeAction(robot,d)" ,"butlerresourcemodel" ) 
						delay(860) 
						forward("modelChangeAction", "modelChangeAction(robot,h)" ,"butlerresourcemodel" ) 
						delay(3000) 
						forward("modelChangeAction", "modelChangeAction(robot,d)" ,"butlerresourcemodel" ) 
						delay(870) 
						forward("modelChangeAction", "modelChangeAction(robot,h)" ,"butlerresourcemodel" ) 
						delay(3000) 
						println("###RIGHT CALIBRATION TERMINATED")
					}
				}	 
			}
		}
}
