/* Generated by AN DISI Unibo */ 
package it.unibo.ctxResourceModelV
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "notcarehost", this, "roomexplvirtual.pl", "sysRules.pl"
	)
}

