/* Generated by AN DISI Unibo */ 
package it.unibo.maitre

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Maitre ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("###Maitre STARTED")
						delay(3000) 
					}
				}	 
				state("finish") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("completedTask(TASK)"), Term.createTerm("completedTask(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Butler finito ${payloadArg(0)} task")
						}
					}
				}	 
				state("updateFP") { //this:State
					action { //it:State
					}
				}	 
				state("updateFC") { //this:State
					action { //it:State
					}
				}	 
				state("updateFA") { //this:State
					action { //it:State
					}
				}	 
			}
		}
}
