/* Generated by AN DISI Unibo */ 
package it.unibo.maitre

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Maitre ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("###Maitre STARTED")
						delay(3000) 
						itunibo.coap.client.maitreClient.createClient(  )
					}
				}	 
				state("sendingP") { //this:State
					action { //it:State
						delay(2000) 
						println("----Maitre send prepare message")
						forward("modelChangeTask", "modelChangeTask(robot,preparing,0,0)" ,"butlerresourcemodel" ) 
					}
					 transition(edgeName="t034",targetState="sendingAC",cond=whenDispatch("completedTask"))
				}	 
				state("sendingAC") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("completedTask(TASK)"), Term.createTerm("completedTask(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Butler finito ${payloadArg(0)} task")
						}
						delay(2000) 
						forward("modelChangeTask", "modelChangeTask(robot,cleaning,0,0)" ,"butlerresourcemodel" ) 
						forward("cl", "cl" ,"maitre" ) 
					}
					 transition(edgeName="t035",targetState="waitingAfAck",cond=whenDispatch("add"))
					transition(edgeName="t036",targetState="waitingClAck",cond=whenDispatch("cl"))
				}	 
				state("waitingAfAck") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t037",targetState="sendingAC",cond=whenDispatch("completedTask"))
					transition(edgeName="t038",targetState="updateFA",cond=whenDispatch("currentFood"))
				}	 
				state("waitingClAck") { //this:State
					action { //it:State
					}
					 transition(edgeName="t039",targetState="finish",cond=whenDispatch("completedTask"))
					transition(edgeName="t040",targetState="updateFC",cond=whenDispatch("currentFood"))
				}	 
				state("finish") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("completedTask(TASK)"), Term.createTerm("completedTask(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Butler finito ${payloadArg(0)} task")
						}
					}
				}	 
				state("updateFP") { //this:State
					action { //it:State
					}
				}	 
				state("updateFC") { //this:State
					action { //it:State
					}
				}	 
				state("updateFA") { //this:State
					action { //it:State
					}
				}	 
			}
		}
}
