/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRoomExplV
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "notcarelocalhost", this, "sprint4.pl", "sysRules.pl"
	)
}

