/* Generated by AN DISI Unibo */ 
package it.unibo.pantry

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Pantry ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Pantry STARTED")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						println("###IN waitCmd Pantry")
					}
					 transition(edgeName="t044",targetState="getting",cond=whenDispatch("getDishesPantry"))
					transition(edgeName="t045",targetState="putting",cond=whenDispatch("putDishesPantry"))
				}	 
				state("getting") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("getDishesPantry(ND,NB,NP)"), Term.createTerm("getDishesPantry(ND,NB,NP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("###pantry in getting")
								var ND = payloadArg(0).toInt()
												var NB = payloadArg(1).toInt()
												var NP = payloadArg(2).toInt()
											itunibo.appliance.Pantry.getPantry().getDishes(ND,NB,NP)
											var string = itunibo.appliance.Pantry.getPantry().toString()
											println(string)
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("putting") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("putDishes(ND,NB,NP)"), Term.createTerm("putDishes(ND,NB,NP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								var ND = payloadArg(0).toInt()
												var NB = payloadArg(1).toInt()
												var NP = payloadArg(2).toInt()
											itunibo.appliance.Pantry.getPantry().putDishes(ND,NB,NP)
											println(itunibo.appliance.Pantry.getPantry().toString())
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
