/* Generated by AN DISI Unibo */ 
package it.unibo.fridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fridge ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var content = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("###Fridge STARTED")
						solve("consult('sysRules.pl')","") //set resVar	
						solve("consult('fridgeContent.pl')","") //set resVar	
						itunibo.coap.resources.fridgeContent.create(myself)
						solve("getFood(L)","") //set resVar	
						if(currentSolution.isSuccess()) { content = getCurSol("L").toString()
						itunibo.appliance.fridgeAppliance.updateContent( content  )
						 }
					}
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="t050",targetState="checking",cond=whenDispatch("foodAvailability"))
					transition(edgeName="t051",targetState="updatingTf",cond=whenDispatch("foodTaken"))
					transition(edgeName="t052",targetState="updatingPf",cond=whenDispatch("foodPutted"))
				}	 
				state("checking") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("updatingTf") { //this:State
					action { //it:State
						var QA = 0; 
								  var Diff = 0
						if( checkMsgContent( Term.createTerm("foodTaken(C,Q)"), Term.createTerm("foodTaken(Code,Quant)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("food(${payloadArg(0)},QA)","") //set resVar	
								if(currentSolution.isSuccess()) { QA = getCurSol("QA").toString().toInt();
												  Diff = QA - payloadArg(1).toString().toInt()
								 }
								solve("updateQuantity(${payloadArg(0)},$Diff)","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("updatingPf") { //this:State
					action { //it:State
						var QA = 0; 
								  var Diff = 0
						if( checkMsgContent( Term.createTerm("foodPutted(C,Q)"), Term.createTerm("foodPutted(Code,Quant)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("food(${payloadArg(0)},QA)","") //set resVar	
								if(currentSolution.isSuccess()) { QA = getCurSol("QA").toString().toInt();
												  Diff = QA + payloadArg(1).toString().toInt()
								 }
								solve("updateQuantity(${payloadArg(0)},$Diff)","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
