/* Generated by AN DISI Unibo */ 
package it.unibo.ctxExploration
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.43.102", this, "sprint3.pl", "sysRules.pl"
	)
}

